import os
import time
import logging
from dotenv import load_dotenv
from sqlalchemy.orm import Session
from backend.database import SessionLocal
from backend import models
import openai

load_dotenv()
logger = logging.getLogger(__name__)

class InstagramService:
    def __init__(self):
        self.token = os.getenv("INSTAGRAM_TOKEN", "mock_token")

    def update_token(self, new_token: str):
        self.token = new_token
        logger.info("Instagram Token updated in memory.")

    def post_image(self, image_path: str, caption: str):
        logger.info(f"Uploading {image_path} with caption: {caption}")

        # --- Real Implementation Guide ---
        # 1. Upload container:
        # url = f"https://graph.facebook.com/v19.0/{PAGE_ID}/media"
        # payload = {"image_url": public_url, "caption": caption, "access_token": self.token}
        # r = requests.post(url, data=payload)
        # container_id = r.json()['id']
        #
        # 2. Publish container:
        # publish_url = f"https://graph.facebook.com/v19.0/{PAGE_ID}/media_publish"
        # r = requests.post(publish_url, data={"creation_id": container_id, "access_token": self.token})
        # ---------------------------------

        time.sleep(2) # Simulate upload time
        if "fail" in image_path:
            raise Exception("Simulated Upload Failure")
        return "success_id_123"

class AIService:
    def __init__(self):
        self.api_key = os.getenv("OPENAI_API_KEY")
        if self.api_key:
            self.client = openai.OpenAI(api_key=self.api_key)
        else:
            self.client = None

    def generate_caption(self, image_path: str):
        if not self.client:
            logger.info(f"Using Mock AI for {image_path}")
            time.sleep(1)
            return "Caption generated by MOCK AI for " + os.path.basename(image_path)

        logger.info(f"Using OpenAI for {image_path}")
        try:
            # Simplified OpenAI call
            response = self.client.chat.completions.create(
                model="gpt-4o",
                messages=[
                    {"role": "system", "content": "You are a creative Instagram caption writer."},
                    {"role": "user", "content": f"Write a caption for an image named {os.path.basename(image_path)}"}
                ]
            )
            return response.choices[0].message.content
        except Exception as e:
            logger.error(f"OpenAI Error: {e}")
            return "Error generating caption."

instagram_service = InstagramService()
ai_service = AIService()

def process_upload(post_id: int):
    """
    Background Task to process the upload.
    Creates its own DB session to be thread-safe.
    """
    db = SessionLocal()
    post = None
    try:
        post = db.query(models.Post).filter(models.Post.id == post_id).first()
        if not post:
            logger.warning(f"Post {post_id} not found in background task.")
            return

        post.status = models.PostStatus.PROCESSING.value
        db.commit()

        # AI Generation (if caption is missing)
        caption = post.caption
        if not caption:
            caption = ai_service.generate_caption(post.image_path)
            post.caption = caption
            db.commit() # Save caption

        # Instagram Upload
        instagram_service.post_image(post.image_path, caption)

        post.status = models.PostStatus.DONE.value
        db.commit()
        logger.info(f"Post {post_id} completed successfully.")

    except Exception as e:
        logger.error(f"Error processing post {post_id}: {e}", exc_info=True)
        if post:
            post.status = models.PostStatus.ERROR.value
            post.error_message = str(e)
            db.commit()

    finally:
        db.close()
